### ISSUE TITLE
Debugger gets temporarily stuck on Linux

### ISSUE THREAD

**Issue by astillich** [dosbox-staging/dosbox-staging#1821]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### What Operating System are you using?

Linux x86_64

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I have just cloned the dosbox-staging main branch and configured it with the debugger enabled. It builds fine, but when I try to run it, it creates two windows which are both not refreshed. The debugger window has contents for a moment, but then blanks itself. The process does not hang, because it outputs "SDL: Window has lost keyboard focus" when the second window loses focus.

Am I doing something wrong, or is the debugger broken ATM? 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Configure dosbox-staging with `meson -Denable_debugger=heavy ../dosbox-staging`
2. Perform a build
3. Run the resulting executable

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by brandonrobertz** [comment]
Debugger is broken and has been for quite some time. I've heard that it works in some very narrow environments, but the debugger certainly needs some love. If you got it working, I'm certain a patch would be appreciated!

**Comment by astillich** [comment]
I might look into it, can anybody give any pointers about what needs to be done? @kklobe you seem to have worked on this. Maybe you have some info?

**Comment by kklobe** [comment]
> I might look into it, can anybody give any pointers about what needs to be done? @kklobe you seem to have worked on this. Maybe you have some info?

if I remember correctly from Discord chats awhile ago, @GranMinigun found out that it was an issue with SDL 2.0.22 on Linux (I just built against main on macOS with 2.0.22 and it's fine). I think there was already a fix in SDL mainline, or backing down to 2.0.20 worked as well. Sorry I don't have much bandwidth to investigate at this point.

**Comment by kcgen** [comment]
Thanks for checking on your side, @kklobe (and hope all is going well!). 

> @GranMinigun found out that it was an issue with SDL 2.0.22 on Linux (I just built against main on macOS with 2.0.22 and it's fine). I think there was already a fix in SDL mainline, or backing down to 2.0.20 worked as well. 

Just pushed branch `kc/cleanup-debugger-1` to (maybe?) fix the window setup order to address this, if you can give it a try. Will PR it shortly.

**Comment by astillich** [comment]
I'll try your branch when I get home.

**Comment by astillich** [comment]
I switched to the branch and did a fresh build. Now the dosbox main window is usable, but the debugger window does not open. I have verified that C_DEBUG is set in config.h, so the build seems to have been configured properly for enabling the debugger.

**Comment by astillich** [comment]
Scratch that, breaking into the debugger brings up the debugger window which seems to work fine.

**Comment by brandonrobertz** [comment]
> And scratch that again: after resuming execution the main window does not update anymore.

Yes, this is the "broken" behavior that I've always seen. Sometimes I can get the debugger window displaying something but it's always frozen.

**Comment by grapeli** [comment]
It is however important exactly which change in SDL has such a negative effect.

It broke exactly on that [commit](https://github.com/libsdl-org/SDL/commit/60ddb74cfe6b8c20a1e0c6afa473990c6467ea40).
With SDL mainline is the same.

**Comment by kcgen** [comment]
from @GranMinigun :
 - Both are unusable, likely due to SDL being bugged. :(
 - Well, with OpenGL output, that is. Texture output seems to work.

For me, the PR gets me a bit further with OpenGL builds, however switching back and fourth between the game and debugger windows can get get either one of them stuck.

Thanks @grapeli. With your information plus what @GranMinigun mentioned, I've added a commit to the branch that knocks out OpenGL specifically for debugger-enabled builds when compiling with SDL >=2.0.20. I don't think there's a version where this is fixed, so the plan will be to leave this open-ended until it's fixed, at which point we can bound that check to a version range.

@astillich , if you can try another build of that branch - curious how it goes!

**Comment by astillich** [comment]
@kcgen It still hangs the main window when I resume execution in the debugger. Both windows paint properly now, though. When breaking and resuming again a few times, breaking into the debugger stops working. When it is in this state, window contents are not refreshed anymore.

**Comment by kcgen** [comment]
> When I extend your added check to include that, I cannot get it to lock up anymore when breaking into the debugger and resuming. 

Thanks @astillich - I've merged the incremental improvement thus far. 

> Sometimes keyboard input does not work in the main window after resuming (the main window is 'active' judging from the title bar but accepts no key input), alt tabbing away and back to it fixes that. 

> And sometimes the debugger window does not refresh when breaking, so there's a line saying "(Running)" while the debugger is in fact in stopped state.

More work is needed to address these eventing/updating issues. 

> I might look into it, can anybody give any pointers about what needs to be done?

With @kklobe's additions, DOSBox-Staging is now a multi-window SDL application, with the second window being PDCurses backed by SDL, and getting events from SDL.

Previously the debugger was drawn using ncurses directly on the console, so SDL didn't really factor into it.

If you drill into sdlmain.cpp, you'll find a big while loop that processes the events (keyboard, mouse, window-state, etc..). 

A design feature that was part of the PDCurses PR was to create an event queue for the PDCurses window, fed via a global queue object: `pdc_event_queue`.

In sdlmain's while loop, you'll see a function that inspects the window ID, and if it's the debugger it will move the event and put in that queue for the debugger, and essentially eat the event (preventing the main window from processing it).

So you can thing of this logic as an event separator/divider.  It took some careful finetuning to get right.

Lazy Foo has a nice guide for multi-SDL window handling: https://lazyfoo.net/tutorials/SDL/36_multiple_windows/index.php, where you can see a different approach to the event processing.

I don't know exactly why these windows get a bit "stuck" and need some alt-tabbing to bring them back to life. It's just a hunch that it might have to do with the eventing, because that's often how changes are driven into these windows.

**Comment by kklobe** [comment]
thanks for the detailed writeup @kcgen! now, just to confirm, are all these reports only from Linux, or are some coming from Windows / macOS?

**Comment by kcgen** [comment]
So far, 100% from Linux land!

With Windows and macOS healthy, it (feels) like a platform-specific bug (likely?) from SDL; although we do have some of our own platform branches in the code, although I don't see any in the window or event handling.

**Comment by kcgen** [comment]
Tagging w/ Linux until we hear otherwise.  Thanks for pointing out that commonality, @kklobe!

**Comment by kklobe** [comment]
I wonder if the list of events in `PDC_pump_and_peep()` in `pdcdisp.cpp` needs to be expanded (among other things). I will get a Linux VM cobbled together here and see if I can get a repro for starters.

**Comment by Burrito78** [comment]
@kklobe @kcgen Any news on this? Keep this open?

**Comment by GranMinigun** [comment]
Debugger was actually working pretty well for me lately. Maybe it should redraw itself on window exposed events, but I can't remember it getting stuck and requiring a resize like before.

**Comment by Grounded0** [comment]
Should be rechecked with DOSBox Staging 0.82.0 RC1. A lot of improvements have gone in to the overall robustness of this feature after the development build being used by the author.

**Comment by Grounded0** [comment]
Will close this as resolved since its stale and GranMinigun seems to indicate no described issue with the debugger on Linux.

**Comment by johnnovak** [comment]
> Will close this as resolved since its stale and GranMinigun seems to indicate no described issue present with the debugger on Linux. No response within a month from the author on my request.

That's fine, but I'd like to ask you not to close tickets and merge in the future. Adding/removing labels is fine, but as you're not a member of the core team, it's best to leave the decision when to close something to us.

**Comment by Grounded0** [comment]
I had extended privileges until late 2023 and after that maintainer privileges issued by you. Since you don't like executive decisions I make its time to ramp down my activities here like GranMinigun.

**Comment by johnnovak** [comment]
> I had extended privileges until late 2023 and after that maintainer privileges issued by you. Since you don't like executive decisions I make its time to ramp down my activities here like GranMinigun.

I did not say to stop contributing; you make a lots of useful contributions which I appreciate.

Just go easy on closing ambiguous and technical tickets, please. This is borderline ok as the debugger would need some love anyway, we know that (but I still don't fully understand what the situation is with the original issue reported here... but it's ok).

**Comment by Grounded0** [comment]
It's about this:

![101355347-b9e56300-3896-11eb-925e-f11fdc00b78c](https://github.com/user-attachments/assets/c7d22b51-c9b9-4d0b-8760-3ac9707dc573)

GranMinigun made a lot of fixes in 2023 to make this more robust. The originating issue of debugger window getting "stuck" isn't observable anymore. I think both SDL windows still don't refresh independently on receiving new output but that was not the scope of this ticket.

**Comment by johnnovak** [comment]
Thanks for the additional details @Grounded0
