### ISSUE TITLE
Read DAC color palette

### ISSUE THREAD

**Issue by vincent-bouffigny** [dosbox-staging/dosbox-staging#2444]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Different version than latest?

0.80.0 / Fedora 37

### What Operating System are you using?

Linux x86_64

### Whats your question and how can we help?

Hi,
I have a little question.
I try to read the r,g,b components of a color but without success.
I changed my color, it's ok on the screen but I can't read the r,g,b values always at 0...
do you have an idea ? Thank you in advance
My graphical card is S3.

Set color 1 OK:
cli
mov dx, 3C8h
mov al, 1
out dx, al
mov dx, 3C9h
mov al, 10		; [r == 10]
out dx, al
mov al, 20		; [g == 20]
out dx, al
mov al, 30		; [b == 30]
out dx, al
sti

Get color 1 KO:
cli
mov al, 1
mov dx, 3C7h
out dx, al
mov dx, 3C9h
in al, dx                 ; [r == 0]
in al, dx                 ; [g == 0]
in al, dx                 ; [b == 0]
sti

### Code of Conduct & Contributing Guidelines

- [x] Yes, I agree.

**Comment by kcgen** [comment]
Inspect src/hardware/vga_dac.cpp

**Comment by vincent-bouffigny** [comment]
already done ...

**Comment by kcgen** [comment]
This area of code hasn't changed from upstream. Do you know if you get the same result with DOSBox SVN or 0.74.3, as well as with DOSBox-X?

**Comment by vincent-bouffigny** [comment]
No i did not try

**Comment by johnnovak** [comment]
Well, it should work as described here:
http://www.osdever.net/FreeVGA/vga/colorreg.htm

There's even some example code here:
http://bos.asmhackers.net/docs/vga_without_bios/docs/palettesetting.pdf

If the example code from the PDF doesn't work, that's a bug and we should fix it.

Having said that, the only programs that would ever read the palette back would be some screen-capture TSRs. 99% of DOS programs either use the BIOS interrupts to set the palette, or simply just keep a cache of the palette values in a 768 byte buffer, do all palette manipulations in-memory (e.g. fades), then output the whole thing in one go to the write port and never read it back. Well, that's how I've always done it in my VGA asm coder days back then. Port I/O was slow therefore it was avoided where not necessary.

So even if this is completely broken, I expect 99.99% of all apps to just work fine, hence quite low priority.

If you can do some more research to find out what's going on that might expedite the fix. Thanks!

**Comment by johnnovak** [comment]
Also, you're not setting the palette mask at 0x3c6; maybe that's the problem.

**Comment by vincent-bouffigny** [comment]
I'll take a look at this, thank you very much!
Yes it may be the mask at 0x3c6 but strange ...

**Comment by vincent-bouffigny** [comment]
I tested the solution with the mask 0x3c6 but it does not solve the problem.
I will test the code on a real PC with an S3 Trio card...

**Comment by johnnovak** [comment]
> I think that in any case, in the "vga_dac.cpp" file, static void write_p3c7(...) { } should not touch vga.dac.write_index but set reading index static void write_p3c8(...) { } should not touch vga.dac.read_index

It's great you tested this on real hardware! Excellent! 🎉 

Like I said, as virtually nothing uses palette reads (I find it likely the BIOS routines themselves also maintained their own "cached" copy of the palette), I'm not surprised that this could be completely broken and everything works happily with zero glitches.

Could you perhaps attempt fixing this yourself @vincent-bouffigny and raise a PR?

Your thoughts @joncampbell123 ?

**Comment by joncampbell123** [comment]
I've come across a few DOS programs (often the Demoscene) that make a few assumptions about reading and writing the palette. In any case according to a laptop I test with that has Paradise chipset, the two registers 3C7h and 3C8h do have a weird relationship with one another and often act like one is off from the other. The DOSBox-X source code regarding this reflects what matches the behavior best.

**Comment by vincent-bouffigny** [comment]
"I test with that has Paradise chipset, the two registers 3C7h and 3C8h do have a weird relationship with one another and often act like one is off from the other", normal the two registers each manage a read/write index !

For having also really coded a lot I know that some cards at the time did not all manage these registers correctly, often the coders also forgot to deactivate the interrupts (cli / sti) during the reads / writes also making results uncertain, moreover the writing buffer of some cards was not completely validated before being able to read the new data, this is also why the 3C7h register in reading returns a "DAC State", but overall these problems were quickly evacuated :
a reading index, an unrelation writing index.

In addition to a fixed PC, I also tested these registers with other VMs like VirtualBox, VMWare, their behavior is also correct.
What is needed is that in the case of DOSBox the functions
static void write_p3c7(...) { } should not touch vga.dac.write_index but only set reading index
and
static void write_p3c8(...) { } should not touch vga.dac.read_index

**Comment by joncampbell123** [comment]
I could test on some more hardware. I was only reporting the findings of a Paradise/Western Digital chipset. I would expect each chipset to have it's own way of handling 3C7h and 3C8h read/write indexes.

I don't think anything ever changes palette from an interrupt handler *and* in the normal code at the same time. Not even the Demoscene would do that.

The way to test 3C8h vs 3C7h indexes is to do something like this:

- Write an index to 3C8h, another index to 3C7h, then write an RGB triad to 3C9h. Which palette index does it update?
- Write another RGB triad again, which index?
- Write an index to 3C8h, then read an RGB triad. Which one did it read?

**Comment by johnnovak** [comment]
> I could test on some more hardware. I was only reporting the findings of a Paradise/Western Digital chipset. I would expect each chipset to have it's own way of handling 3C7h and 3C8h read/write indexes. I'm only saying that maybe the hardware doesn't quite have two independent indices for read/write and maybe they're linked internally somehow.
> 
> I don't think anything ever changes palette from an interrupt handler _and_ in the normal code at the same time. Not even the Demoscene would do that.
> 
> The way to test 3C8h vs 3C7h indexes is to do something like this:
> 
>     * Write an index to 3C8h, another index to 3C7h, then write an RGB triad to 3C9h. Which palette index does it update?
> 
>     * Write another RGB triad again, which index?
> 
>     * Write an index to 3C8h, then read an RGB triad. Which one did it read?

Ok but the very first example in the top thread still semm to be a bug, no?

**Comment by joncampbell123** [comment]
No problems here in DOSBox-X, machine=svga_s3.

![debug_000](https://user-images.githubusercontent.com/6245486/236343066-2c724e69-2c7a-4ba8-bb67-41a0707facee.png)
![debug_001](https://user-images.githubusercontent.com/6245486/236343070-5833390a-9c48-48e9-9ae8-947949902325.png)
![debug_002](https://user-images.githubusercontent.com/6245486/236343073-a3caaf7d-740c-4b10-acc3-49e2c53c1044.png)
![vgapal](https://user-images.githubusercontent.com/6245486/236343075-c2876bae-25dc-47fb-9fd9-b6118b5b2bc3.png)

This is how DOSBox-X is emulating those registers: https://github.com/joncampbell123/dosbox-x/blob/master/src/hardware/vga_dac.cpp#L243

**Comment by joncampbell123** [comment]
If the debugger interface is available, DOSBox-X has a "VGA DACPAL" command to dump to console all 256 colors of the palette.

**Comment by joncampbell123** [comment]
Staging doesn't appear to have the bug either.

![debug_000](https://user-images.githubusercontent.com/6245486/236344303-05174caa-dc9a-4cc7-a797-6f378fe2e01e.png)
![debug_001](https://user-images.githubusercontent.com/6245486/236344304-4bc5d291-2e73-4284-90dd-10afa72da0b2.png)
![debug_002](https://user-images.githubusercontent.com/6245486/236344306-551f03c9-46f1-4069-b432-79378b54a433.png)

**Comment by johnnovak** [comment]
Thanks a lot @joncampbell123 for spending time on this & testing it!
@vincent-bouffigny is it possible that something went wrong during your initial testing? Can you try again and confirm Jon's results, then we can close this as it seems to be working as it should?

**Comment by kcgen** [comment]
> Thanks a lot @joncampbell123 for spending time on this & testing it!

Here here to that; thank you as well, @johnnovak :beers:

**Comment by vincent-bouffigny** [comment]
yes really strange ... I will redo the tests
thank you for everything ;)

**Comment by vincent-bouffigny** [comment]
yes really strange ... I will redo the tests
thank you for everything ;)

**Comment by vincent-bouffigny** [comment]
Yes i confirm that it works with debug command, on dosbox-x, staging, etc..
I can't explain it to myself, it's certainly a side effect of my program, yet very controlled ... if I find where my problem comes from, I'll give you a feedback.
thank you for your involvement

c:\debug
-o 3c8, 1
-o 3c9, 10
-o 3c9, 20
-o 3c9, 30

reading
-o 3c7, 1
check write index
-i 3c8 => 02 ok

-i 3c9 => 10 ok
-i 3x9 => 20 ok
-i 3x9 => 30 ok

-i 3c7 => 03  dac state ok

.... computer science mystery

**Comment by joncampbell123** [comment]
> Well, it should work as described here: http://www.osdever.net/FreeVGA/vga/colorreg.htm
> 
> There's even some example code here: http://bos.asmhackers.net/docs/vga_without_bios/docs/palettesetting.pdf
> 
> If the example code from the PDF doesn't work, that's a bug and we should fix it. There should be zero difference between VGA and SVGA/VESA.
> 
> Having said that, the only programs that would ever read the palette back would be some screen-capture TSRs. 99% of DOS programs either use the BIOS interrupts to set the palette, or simply just keep a cache of the palette values in a 768 byte buffer, do all palette manipulations in-memory (e.g. fades), then output the whole thing in one go to the write port and never read it back. Well, that's how I've always done it in my VGA asm coder days back then. Port I/O was slow therefore it was avoided where not necessary.
> 
> So even if this is completely broken, I expect 99.99% of all apps to just work fine, hence quite low priority.
> 
> If you can do some more research to find out what's going on that might expedite the fix. Thanks!

Looking at the PDF, I don't think this guy understands what port 0x3C6 really is.

It's not a mask that controls which palette bits you can change, that's the PEL MASK register through which every 8-bit value sent to the DAC is masked by. It's normally 0xFF so you get all 256 colors, but you can limit the display to the first 16 colors by writing 0x0F. But as far as I know that register has no effect on 3C7h, 3C8h, 3C9h.

**Comment by joncampbell123** [comment]
> Well, it should work as described here: http://www.osdever.net/FreeVGA/vga/colorreg.htm
> 
> There's even some example code here: http://bos.asmhackers.net/docs/vga_without_bios/docs/palettesetting.pdf
> 
> If the example code from the PDF doesn't work, that's a bug and we should fix it. There should be zero difference between VGA and SVGA/VESA.
> 
> Having said that, the only programs that would ever read the palette back would be some screen-capture TSRs. 99% of DOS programs either use the BIOS interrupts to set the palette, or simply just keep a cache of the palette values in a 768 byte buffer, do all palette manipulations in-memory (e.g. fades), then output the whole thing in one go to the write port and never read it back. Well, that's how I've always done it in my VGA asm coder days back then. Port I/O was slow therefore it was avoided where not necessary.
> 
> So even if this is completely broken, I expect 99.99% of all apps to just work fine, hence quite low priority.
> 
> If you can do some more research to find out what's going on that might expedite the fix. Thanks!

Most DOS programs DO cache the palette as they work with it, but I've seen a few that really do rely on reading back the palette to write it again. One that I came across while developing the "8-bit DAC mode" VESA BIOS extensions in DOSBox-X is "Amulets and Armor". You have to mask the palette bytes by 0x3F because it uses palette fades with signed char and leaving all 8 bits open causes funny overbright effects on screen otherwise.

**Comment by johnnovak** [comment]
> One that I came across while developing the "8-bit DAC mode" VESA BIOS extensions in DOSBox-X is "Amulets and Armor". You have to mask the palette bytes by 0x3F because it uses palette fades with signed char and leaving all 8 bits open causes funny overbright effects on screen otherwise.

Interesting info @joncampbell123. That a bit of a shit technique on the side of the guy who wrote that game though.

Thanks for confirming this is not a bus @vincent-bouffigny.

**Comment by vincent-bouffigny** [comment]
Je confirme que le registre du masque pel n'a aucun effet sur 3C7h, 3C8h, 3C9h...

**Comment by johnnovak** [comment]
> Je confirme que le registre du masque pel n'a aucun effet sur 3C7h, 3C8h, 3C9h...

Um, English?
