### ISSUE TITLE
Allow extended precision floating point calculations to be done in software

### ISSUE THREAD

**Issue by Grounded0** [dosbox-staging/dosbox-staging#3125]
### Are you using the latest Dosbox-Staging Version?

- [X] I have checked releases and am using the latest release.

### Is your feature request related to a problem? Please describe.

Currently any hardware that doesn't support IEEE 754 extended precision format (80-bit) is doing calculations in double precision (64-bit) format when it sees an x87 instruction. There should be a configuration option to enable extended precision formats to be calculated in software.

Possibly connected issues and PRs:

- ~~#610~~
- ~~#2404~~
- ~~#1231~~
- ~~#2900~~

And a lot of stuff we're not even aware of yet.

### Describe the solution you'd like

There should be a configuration option to enable extended precision formats to be calculated in software.

It could have smart analysis of incoming x87 instructions:

x87 extended precision format => calculate in software
x87 double precision and below format => calculate by hardware

Old x86 and 68k processors without FPUs did all floating point calculation in software when program used a floating point instruction. Now we would only need to calculate extended precision formats in software through smart analysis of the instructions.

### Describe alternatives you've considered

I can't think of anything except using architectures with quadruple precision floating point in hardware and doing extended precision in `binary128` or sticking with x86-64 with its register level x87 support.

### Code of Conduct & Contributing Guidelines

- [X] Yes, I agree.

**Comment by weirddan455** [comment]
>  Old x86 and 68k processors without FPUs did all floating point calculation in software when program used a floating point instruction.

I don't think this is true regarding old x86 processors (I don't know about 68k but that's not very relevant to Dosbox).  I believe if you don't have an FPU (either a separate x87 co-processor or one that's built-in to the main CPU), you simply cannot execute floating point instructions.  The executable should either crash or throw an error.

Games, on the other hand, could emulate this in software using integer instructions.  Usually this was fixed-point though, not floating-point at all.  There's nothing we as an emulator need to do for this case.  It's all handled in game code.

Also, note that this should only be a problem on non-x86 systems.  On x86, those x87 instructions are still available in hardware on modern CPUs (and I seem to recall someone tested that we are using them to 80-bit precision).

On ARM, we probably would need software emulation if we want 80-bit precision.  Doing so will help accuracy but is likely to cause a significant hit to performance (how much it will hurt is hard to say).

**Comment by johnnovak** [comment]
The FPU only got integrated into the CPU starting with the 486 (except for the 486DLC range). But as it was rather slow, it wasn't used for much in games and demos, except for precalculating values for lookup tables at startup perhaps (e.g., sin/cos tables were super common), but those were stored as 16.16 fixed-point values in 32-bit integers, so FPU precision did not even come into the picture.

The FPU only became fast enough with the Pentiums for real-time use. The details are a bit murky, but certain games just went for full 80-bit precision, and I think internally the precision was always 80-bits anyway (but I'm not an expert). See this post for details:

https://stackoverflow.com/questions/59094449/did-old-dos-c-compilners-implement-double-as-32-bit

The thing is, very few games used the FPU, but for the ones that did use it, it was pretty much mandatory. And the main reason was precision as you could still do about 3 times faster fixed-point math with integer registers on the Pentium, but at a vastly reduced precision. So even if we could implement a faster reduced precision path and detect what the game uses, probably it wouldn't help. But it might be hard/impossible to detect it, and if the game assumed 80-bit internal precision anyway (even when working with 32/64-bit floats), we're back to the same problem.

Btw, one of the very few DOS games that uses the FPU, Quake, can't even run without one:
https://www.vogons.org/viewtopic.php?t=69324

We could do an interesting special hack to make a special trick work when FPU registers are used to transfer 64-bit integers:
https://github.com/joncampbell123/dosbox-x/issues/119

That's a different issue, but worth mentioning.

I'm actually wondering why the handful of DOS games that require an FPU don't misbehave more with 64-bit floats... But maybe Elite 2 does, it just doesn't happen all the time?

**Comment by Grounded0** [comment]
Pinging @dancek since he talked to me about working on the FPU stuff... in 2022. 😁

**Comment by Grounded0** [comment]
Precision control in 80486 FPU:

<img width="831" alt="Screenshot 2023-11-16 at 2 53 23" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/43e89d7d-cdae-46b3-8d8b-d18364e8f1a5">

<img width="899" alt="Screenshot 2023-11-16 at 2 44 48" src="https://github.com/dosbox-staging/dosbox-staging/assets/48192273/44b59333-d0c8-498f-b5b1-4ba376156d0a">

**Comment by Grounded0** [comment]
If we're being hit with:

00 => hardware
10 => hardware
11 => hardware (x86-64) or software (everything else)

**Comment by johnnovak** [comment]
> If we're being hit with:
> 
> `00` => hardware `10` => hardware `11` => hardware (x86-64) or software (everything else)
> 
> I call this Float Point Precision Predecoder Engine or FPPPE. 🙂

Thanks @Grounded0 -- now make it happen! 😆 It would be an interesting research project for someone who loves to tinker with low level CPU/FPU emulation.

**Comment by Torinde** [comment]
I agree it'll be useful. Even if performance is not yet sufficient on some hosts.
- non-x86 CPUs don't support 80-bit floats and many don't support 128-bit either
- MSVC doesn't support 80-bit floats
- eventually x86-64 CPUs will drop the x87 stack (the [x87, MMX, and 3DNow! instruction sets are already deprecated in 64-bit modes](https://learn.microsoft.com/en-us/windows/win32/dxtecharts/sixty-four-bit-programming-for-game-developers) on Windows; there is the example of the planned [x86-S](https://en.wikipedia.org/wiki/X86-64#x86-S) dropping 16-bit modes)

86Box recently added Softfloat, I think. It would be great if 80-bit precision and anything else using x87 registers (x87, **MMX, 3DNow!**) gets supported via software emulation.

**Comment by Grounded0** [comment]
@dancek 

Intel Math CoProcessor Advanced Diagnostics:

https://anttipeltola.eu/misc/files/MCPDIAG.ZIP

**Comment by Grounded0** [comment]
If i run Comprehensive Floating Point Conformance Test on macOS/x86-64 i get 0 errors currently on all tests because its done on x87 with up to 80-bit extended precision.

On macOS/ARM64 we get thousands of errors due to 80-bit extended precision being truncated to 64-bit double precision.

**Comment by Grounded0** [comment]
As for performance see:

https://github.com/dosbox-staging/dosbox-staging/issues/3125#issuecomment-1813537700

https://github.com/dosbox-staging/dosbox-staging/issues/3125#issuecomment-1813564974

**Comment by Grounded0** [comment]
Performance sucked so bad on the x87 until Pentium that programmers probably were wary of using 80-bit extended precision unless absolutely necessary. That's probably the reason we're seeing so few issues related to extended precision on architectures other than x86-64 as programmers probably flagged their calculations as `00` single precision and `10` double precision to optimise performance.

**Comment by dancek** [comment]
I guess the instructions that may change the control word are
- `FINIT` / `FNINIT` (set CW to `037F`, ie. extended precision)
- `FLDCW` / `FLDENV`
- `FRSTOR` / `FXRSTOR`
so checking those should be enough to know which precision is being used.

Of course actually implementing the 80-bit operations accurately in software is going to be a lot of work. And if we want support for both quad precision (128-bit) and double precision (64-bit) platforms, we need two implementations.

**Comment by dancek** [comment]
At a glance it seems like compiling software that uses `__float128` is not trivial even on platforms supporting it. It will probably only be possible using GCC + libquadmath. And I haven't found a reference on which aarch64 processors support 128-bit floats, though it does seem at least some Apple silicon does.

**Comment by Grounded0** [comment]
I think it's mainly currently for our `ppc64le` platform which we also have as a CI runner. It's probably better to concentrate all resources to extended precision for 64-bit double precision systems for now. ARM64 doesn't do `float128` without SVE which is an optional feature in ARMv8 and currently not supported by Apple silicon.

**Comment by dancek** [comment]
Right, so the occasional person claiming to have compiled float128 code for Apple M1 is just plain mistaken. :joy: 

At least that makes the implementation easier and more portable.

**Comment by johnnovak** [comment]
Again, if someone wants to fiddle with this, be my guest, but almost nothing _needs_ the FPU:

https://www.vogons.org/viewtopic.php?t=42672

**Comment by kcgen** [comment]
> implementing the 80-bit operations accurately in software is going to be a lot of work. 

Good news is there a lots of multi and extended precision floating point libs out there.

They continue to be maintained and evolved to be cross-platform and very fast. MPIR is a big one (still going from 1991, MP being multi-precision):

https://github.com/BrianGladman/mpir

> If the C type `double` doesn't give enough precision for your application, declare your variables as `mpf_t` instead, set the precision to any number desired, and call the functions in the mpf class for the arithmetic operations.

@kklobe did some digging and found a nice lib too; it might be more C++ and use more SIMD calls on all the platforms, but I can't recall it. (definitely in one of the FPU related GitHub tickets)!

Really glad you're checking this out, @dancek !

**Comment by kklobe** [comment]
> > implementing the 80-bit operations accurately in software is going to be a lot of work.
> 
> Good news is there a lots of multi and extended precision floating point libs out there.
> 
> They continue to be maintained and evolved to be cross-platform and very fast. MPIR is a big one (still going from 1991, MP being multi-precision):
> 
> https://github.com/BrianGladman/mpir
> 
> > If the C type `double` doesn't give enough precision for your application, declare your variables as `mpf_t` instead, set the precision to any number desired, and call the functions in the mpf class for the arithmetic operations.
> 
> @kklobe did some digging and found a nice lib too; it might be more C++ and use more SIMD calls on all the platforms, but I can't recall it. (definitely in one of the FPU related GitHub tickets)!
> 
> Really glad you're checking this out, @dancek !

Yeah, I did a quick test of MPFR and it was painfully slow: https://github.com/dosbox-staging/dosbox-staging/issues/2900#issuecomment-1740072236

I also looked into SoftFloat as a possibility, seemed pretty high-quality: http://www.jhauser.us/arithmetic/SoftFloat.html

**Comment by kklobe** [comment]
> But I don't think that's true. Single precision is useless, you could use integer maths for that and it would be much faster, as I explained. If something _needs_ the FPU, it needs it because it _needs_ extended precision. Like orbital calculations in space sims, etc. Otherwise why bother, they could just do integer math and be 3x faster.

The transcendental and algebraic functions are going to be significantly faster in dedicated floating point hardware, even for single precision, than good fixed-point code.

**Comment by kklobe** [comment]
The MPFR basic arithmetic operations are much faster than the math functions.

Quick benchmark: https://gist.github.com/kklobe/2df6ac7d485dce90a51c430c6fbdf978

```log
Native (double) arithmetic: 5768 microseconds
Native (double) math functions: 4142 microseconds
MPFR (80-bit) arithmetic: 51880 microseconds
MPFR (80-bit) math functions: 1295130 microseconds
ratio of MPFR/native arithmetic: 8
ratio of MPFR/native math functions: 312
```

Perhaps a config option to enable extended precision for different operations? Maybe the games/apps in question don't need extended on cos/sin/sqrt, just basic math?

Seems like a hacking session is in order...

**Comment by kklobe** [comment]
OK, did a quick test replacing `FPU_FADD`,`FPU_FSUB`,`FPU_FMUL`, and `FPU_FDIV` with MPFR 80-bit, and it dropped my QTD scores right about in half (~64 vs. ~120). Definitely still playable.

**Comment by Grounded0** [comment]
@kklobe 

That's wonderful. That's without the predecoder engine we're planning with @dancek to optimise performance. 👍

**Comment by johnnovak** [comment]
Cool stuff guys 😎 Out of interest, now I'm curious of the concrete list of games that either:

- Require an FPU to be present, so no FPU, no game (I know only Quake)
- Can benefit from an FPU but run without one (some late 90s flight/space sims I guess)

Then once we have a list, we could tag it with what precision / instructions the game actually uses. Then we could also note whether it actually misbehaves due to the lack of 80-bit precision mode or not.

I could not find similar lists elsewhere, so it would pretty useful for testing purposes too.

**Comment by johnnovak** [comment]
> The transcendental and algebraic functions are going to be significantly faster in dedicated floating point hardware, even for single precision, than good fixed-point code.

That's cool, but show me a single game or demo that use them in realtime 😄 Sin/cos tables + fixed point + some faked fast square root was still a few times faster and did the job just fine, so that's all everybody did.

Maybe Falcon 3.0 and other Spectrum Holobyte games with FPU support are different, but I doubt it.

I'm not exactly arguing here, I'm plain curious now :) 3D Studio and similar software surely used all of the FPU heavily, but games, I'd don't think so.

**Comment by Grounded0** [comment]
Start logging incoming `FPU_FADD`, `FPU_FSUB`, `FPU_FMUL`, and `FPU_FDIV` and:

`FINIT` / `FNINIT`
`FLDCW` / `FLDENV`
`FRSTOR` / `FXRSTOR`

for incoming control words for precision control so we have an idea how much floating point is used per program basis and more importantly:

How many fall as percentage into 32-bit single precision bucket.
How many fall as percentage into 64-bit double precision bucket.
How many fall as percentage into 80-bit extended precision bucket.

Ends speculation and allow making decisions based on data. 🙂

**Comment by johnnovak** [comment]
> Start logging incoming `FPU_FADD`, `FPU_FSUB`, `FPU_FMUL`, and `FPU_FDIV` as pure count and:
> 
> `FINIT` / `FNINIT` `FLDCW` / `FLDENV` `FRSTOR` / `FXRSTOR`
> 
> for incoming control words for precision control so we have an idea how much floating point is used per program basis and more importantly:
> 
> How many instructions fall as percentage into 32-bit single precision bucket. How many instructions fall as percentage into 64-bit double precision bucket. How many instructions fall as percentage into 80-bit extended precision bucket.
> 
> Ends the speculation and allows making decisions based on hard data. 🙂

Would be cool to write some util that tries to do static analysis on the eXoDOS v6 data and look for these FPU instructions in the binaries. Of course, theres's always compressed code and self-modifying code, but it's better than nothing.

**Comment by kklobe** [comment]
I'm extremely skeptical in general that the math required by a game is going to be sensitive enough to ~16 digits after the decimal point vs ~20 digits to cause rendering issues.

I've done some debugging today with Carmageddon, and, I know Qbix said it was an FPU precision issue, but it looks more like memory corruption to me. The floating point operations that are called during the initial screen with the vertical lines are FIST and FILD, which only work with 16, 32, or 64 bit values; extended precision doesn't enter into it.

I also put log statements in `FPU_ST80` and `FPU_FLD80` as well as the math functions, and they don't even get called leading up to this screen, except for one single `FDIV` at the very beginning.

The values getting loaded and stored are quite suspect. They start out reasonable, with zeroing, but then come the repeated byte patterns:

```log
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af910
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 359978
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 359998
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 3599b8
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 3599d8
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 3599f8
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 359a18
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 359a38
2023-11-22 20:05:37.552 | FLD_I64: 0, addr: 359a58
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af9d8
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af9f8
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af9b8
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af998
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af978
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af958
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af938
2023-11-22 20:05:37.552 | FST_I64: 0, addr: af918
2023-11-22 20:05:37.679 | FLD_I64: 43aa1a1a1a1a1a1a, addr: 34a060
2023-11-22 20:05:37.679 | FLD_I64: 43b7171717171717, addr: 34a080
2023-11-22 20:05:37.679 | FLD_I64: 43b7171717171717, addr: 34a0a0
2023-11-22 20:05:37.679 | FLD_I64: c3b6f3f2f116f4f3, addr: 34a0c0
2023-11-22 20:05:37.679 | FLD_I64: 43a8181a1c1c1e1e, addr: 34a0e0
2023-11-22 20:05:37.679 | FLD_I64: 43ac1c1c1c1c1c1c, addr: 34a100
2023-11-22 20:05:37.679 | FLD_I64: 43c40b940b87070c, addr: 34a120
2023-11-22 20:05:37.679 | FLD_I64: c3d83e3e3e7e98ff, addr: 34a140
2023-11-22 20:05:37.679 | FST_I64: 43c40b940b87070c, addr: a00c0
2023-11-22 20:05:37.679 | FST_I64: c3d83e3e3e7e98ff, addr: a00e0
2023-11-22 20:05:37.679 | FST_I64: 43ac1c1c1c1c1c1c, addr: a00a0
2023-11-22 20:05:37.679 | FST_I64: 43a8181a1c1c1e1e, addr: a0080
2023-11-22 20:05:37.679 | FST_I64: c3b6f3f2f116f4f3, addr: a0060
2023-11-22 20:05:37.679 | FST_I64: 43b7171717171717, addr: a0040
2023-11-22 20:05:37.679 | FST_I64: 43b7171717171717, addr: a0020
```

I can verify these are the two functions that are affecting the screen, since by commenting out one of the `mem_readd` or `mem_writed` calls, the veritcal junk lines double in width.

I am going to see if I can get a working 32-bit Windows build going and report back.

**Comment by johnnovak** [comment]
@kklobe Sounds like the FILD/FIST hack issue that I mentioned above:

https://github.com/joncampbell123/dosbox-x/issues/119

I'd say getting the PCem workaround for that is a _lot_ more important and it would solve a lot more real-world compatiblity problems than adding "proper" 80-bit float support. Just a hint before someone sinks 100+ hours into this 😄

**Comment by kklobe** [comment]
Thanks @johnnovak hadn't followed that link yet, makes perfect sense for what I am seeing, will keep digging into this a bit more, it's been very educational.

And fully agree with your comment re:Quake.

**Comment by johnnovak** [comment]
To be clear, I'm not trying to curb anyone's enthusiasm here; anyone, please feel free to sink massive amounts of time into this if it interests you! I've done a similar thing with the VESA double-scanning / aspect ratio stuff earlier this year and I don't regret it, and DOSBox Staging is better for it 😎 

I'm merely suggesting to address the actually easy-to-do things first that would solve lots of known real-world problems (e.g. to allow the relatively commonly used FILD/FIST trick). Like @Grounded0 likes to say, pick the low-hanging fruits first before planting your own orchard 🍏 🥭 🍐 🍇 😎 (I added that last bit, okay 😅)

While "true 80-bit precision" would be nice in an abstract sense, it's very doubtful it will make much or any difference to actual games (my educated guess is no, it won't). This is similar to emulating MMX instructions; nice in an abstract sense, would be a lot of work (and maitenance effort!), and in the end _maybe_ it would cause a minor difference in a single game.

The situation for applications like modelling software could be different, though, but I'm not qualified to make an assessment about that.

**Comment by johnnovak** [comment]
> Thanks @johnnovak hadn't followed that link yet, makes perfect sense for what I am seeing, will keep digging into this a bit more, it's been very educational.
> 
> And fully agree with your comment re:Quake.

Check this comment too. There are some actual games being mentioned there that seem to use the trick:

https://github.com/joncampbell123/dosbox-x/issues/119#issuecomment-169896711

**Comment by Grounded0** [comment]
@dancek 

Suggest calling this off for now since the developers are using x87 registers in a very naughty way and this will not solve Carmageddon and Quake compatibility issues for non-x86 architectures:

https://github.com/dosbox-staging/dosbox-staging/issues/3125#issuecomment-1823774126

You can of course continue working on this as a hobby project and we'll likely merge an IEEE 754-1985 conformant implementation of this because DOSBox Staging sadly is currently being used by civil engineers and civil engineering students to run early 1990s DOS software to calculate tensile and compressive forces on bridges and so on according to @kcgen . 😞

**Comment by MasterO2** [comment]
> You can of course continue working on this as a hobby project and we'll likely merge an IEEE 754-1985 conformant implementation of this because DOSBox Staging sadly is currently being used by civil engineers and civil engineering students to run early 1990s DOS software to calculate tensile and compressive forces on bridges and so on according to @kcgen. 😞

One would think by now those civil engineers and civil engineering students would be using much more modern software for this.

**Comment by johnnovak** [comment]
> DOSBox Staging sadly is currently being used by civil engineers and civil engineering students to run early 1990s DOS software to calculate tensile and compressive forces on bridges and so on according to @kcgen

😬 

That's one scary thought... We should a big warning sign on our about page saying that numerical compatibility with MS-DOS software running on an actual x86 PC is by _no means_ guaranteed. Use at your risk! (I'm not joking, this can lead to serious consequences if one is unaware...)

**Comment by johnnovak** [comment]
(Some nice sizecoding stuff on your page btw @dancek 😎 🤘🏻 )

**Comment by weirddan455** [comment]
>  Mainly because DOSBox Staging sadly is currently being used by civil engineers and civil engineering students to run early 1990s DOS software to calculate tensile and compressive forces on bridges and so on according to @kcgen . 😞

Holy shit.  If you've ever wondered why every open source license worth using has a "don't sue me" clause... that's why.

You know the old saying:  If your software isn't broke... run it on a gaming emulator programmed by volunteers in their underwear with "Staging" in the name.  Or something like that...

**Comment by johnnovak** [comment]
> > Mainly because DOSBox Staging sadly is currently being used by civil engineers and civil engineering students to run early 1990s DOS software to calculate tensile and compressive forces on bridges and so on according to @kcgen . 😞
> 
> Holy shit. If you've ever wondered why every open source license worth using has a "don't sue me" clause... that's why.
> 
> You know the old saying: If your software isn't broke... run it on a gaming emulator programmed by volunteers in their underwear with "Staging" in the name. Or something like that...

I guess applying common sense always applies when using random software, but arguably you need to be very technical to be aware of this FPU precision issue with PC/MS-DOS emulators. _"Most games I tried work, so I see no reason why INSERT RANDOM APPLICATION wouldn't work either! What can go wrong"_ (a LOT, actually 😅)

Having said that, most disclaimer sections are a bit of a joke, but I guess you really need them in America where everybody just _loves_ to sue. I made a joke of that in my app 😄 

https://gridmonger.johnnovak.net/#Disclaimer

**Comment by dancek** [comment]
> @kklobe
> 
> That's wonderful. That's without the Floating Point Precision Predecoder Engine (FPPPE) we're planning with @dancek to optimise performance. 👍

I'll just note that since adjusting the FPU state is a bit cumbersome I don't think any game would change the control word after initialization. So this optimization would be helpful for avoiding a performance hit for single/double precision games automatically even when the accurate software emulated FPU is enabled.

I also took a quick glance at the 80-bit implementations in Berkeley SoftFloat and I'll guesstimate it's at least a 100x slower than 64-bit floats on hardware. Probably not an issue in many cases, but Quake might actually become annoyingly sluggish if it's running at only 900fps for you now :joy:

**Comment by Grounded0** [comment]
Updated the ticket with the fact that it will NOT close tickets related to Carmageddon and Quake on non-x86 architectures when implemented.

**Comment by MasterO2** [comment]
For what it's worth:

https://www.reddit.com/r/Daggerfall/comments/524hqe/daggerfall_performance_tweaks/

Reddit user `cyandyedeyecandy` says:

`Another option: fpu 1 which I assume enables floating-point calculations. I thought that might be a good idea to enable on processors with a fast FPU (like my Pentium 2). Turns out it doesn't really make a difference most of the time, but in some places it really tanks the frame rate. Experiment with this if you want, it didn't work for me.`

**Comment by kklobe** [comment]
Getting there...

![CleanShot 2023-11-24 at 14 32 20@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/91051879-d159-4710-b86e-1a9db51459ee)

**Comment by johnnovak** [comment]
> Getting there...
> 
> ![CleanShot 2023-11-24 at 14 32 20@2x](https://private-user-images.githubusercontent.com/541026/285541064-91051879-d159-4710-b86e-1a9db51459ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NjEwMzIsIm5iZiI6MTcwMDg2MDczMiwicGF0aCI6Ii81NDEwMjYvMjg1NTQxMDY0LTkxMDUxODc5LWQxNTktNDcxMC1iODZlLTFhOWRiNTE0NTllZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNFQyMTE4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGM5ODI5NWQ5YjEwNmY0ZGFkMmQ0MjZhNTBhMGIwYjk1YjRhNzcyMjZkYmYxYTYwZGQ3NGQxYTBiZWY0OGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LjUtEjAEpCmDxCA-8FVpFxWsAsz_FMQGze6868lF7UQ)

Crikey! 😎 Cool stuff! I will attach a few demos plagued by the vertical stripes problem shortly for testing purposes, stay tuned @kklobe.

**Comment by kcgen** [comment]
Looks like some long cemented-in apple carts are being blown off their foundations! :exploding_head: :boom:

This is remarkable @kklobe ! :rocket:

**Comment by johnnovak** [comment]
Here's some test material @kklobe. Lots of vertical line bugs in these; apparently the guys are using the float-fast-copy-trick to the max! 😎 🤘🏻 

"Sunflower" is a very good performance test as well as they're using the trick in the 3D-rendered scenes (at 70 FPS with 150k cycles).

Note: There might be another unrelated bug plaguing Sunflower (and a few other demos), where the 100% white colour sometimes "wraps over" into 100% black... But that's a separate issue, just mentioning it so you won't be confused by it (if I'm right).

[Multikolor-Kolor.zip](https://github.com/dosbox-staging/dosbox-staging/files/13462513/Multikolor-Kolor.zip)

[Sunflower-Pulse.zip](https://github.com/dosbox-staging/dosbox-staging/files/13462515/Sunflower-Pulse.zip)


## Multikolor by Kolor

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/2f0ff4f1-b4e2-4112-a69b-e5b43e60b93c">


## Sunflower by Pulse

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/c9271e84-4d65-4b97-8979-e6789b0d712c">

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/9ad85b57-2b2b-4b30-9449-2c3a09ca97bc">

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/f5f78608-2194-48c4-9637-c64b61330fe8">

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/ff7657e3-a94f-48d7-9761-39618103ffbb">

<img width="1215" alt="image" src="https://github.com/dosbox-staging/dosbox-staging/assets/698770/8e812af1-f713-496c-9479-1329ceeadb59">

**Comment by kklobe** [comment]
Don't get too excited yet - I'm still at the phase where making Carmageddon work crashes Quake!

**Comment by kklobe** [comment]
@johnnovak well, so far... (Quake as an example of non-trick-using FIST/FILD).

![CleanShot 2023-11-24 at 21 43 57@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/8b88fa02-5e51-4cff-8e26-4030fb50b015)
![CleanShot 2023-11-24 at 21 43 37@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/ebf4c850-e7f0-4973-bfa4-83edb5e150f0)
![CleanShot 2023-11-24 at 21 45 03@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/e92acd9e-d320-4cbb-aa48-41b6a3ce639d)
![CleanShot 2023-11-24 at 21 46 30@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/ab03944d-3009-4637-adbb-ed6bf0b76b5f)

**Comment by johnnovak** [comment]
@kklobe  That's some stellar progress, man! 👍🏻

**Comment by Grounded0** [comment]
This game should also be a test case:

[Motor Mash (1997)](https://www.mobygames.com/game/57275/motor-mash/)

**Comment by kklobe** [comment]
> This game should also be a test case for vertical lines:
> 
> [Motor Mash (1997)](https://www.mobygames.com/game/57275/motor-mash/)

Another good test, thank you!

![CleanShot 2023-11-25 at 05 28 35@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/e60da2ed-be0e-41dd-8b73-7252b953a1e9)
![CleanShot 2023-11-25 at 05 27 24@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/37208eaa-990f-46a7-b63e-f36b4cc86b0a)

**Comment by Grounded0** [comment]
Added vertical lines ticket back so this can operate as a "monitor if issues are fixed" clearing house.

**Comment by kklobe** [comment]
[Pete Sampras Tennis 97](https://www.mobygames.com/game/7250/pete-sampras-tennis-97/) is another one.

![CleanShot 2023-12-02 at 16 24 19@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/22d44153-00fa-4ef3-8c67-957ed602e605)

![CleanShot 2023-12-02 at 16 24 47@2x](https://github.com/dosbox-staging/dosbox-staging/assets/541026/8808c02c-ee78-43e3-a005-af5b6b11f17e)

**Comment by Grounded0** [comment]
We've fixed these FILD/FIST memcpy tricks:

- #3151 

Only game we know failing due to lack of extended precision math is Critical Path (😁);

- #610

**Comment by Grounded0** [comment]
Dropping https://github.com/dosbox-staging/dosbox-staging/labels/game%20compatibility because the game runs properly on the x86. We use https://github.com/dosbox-staging/dosbox-staging/labels/non-x86 now to label these issues.

**Comment by Grounded0** [comment]
> Supported OS
>
> • macOS (Intel CPU)

Most of our non-x86 users are using macOS/ARM64 so probably not.

**Comment by johnnovak** [comment]
> I see [xbyak](https://github.com/herumi/xbyak):
> 
> > a JIT assembler for x86(IA-32)/x64(AMD64, x86-64) MMX/SSE/SSE2/SSE3/SSSE3/SSE4/FPU/AVX/AVX2/AVX-512 by C++ header
> 
> FPU by header file? Can that help here?

We still don't have conclusive proof that 80-bit FPU emulation is required. If no DOS game uses it, it's rather pointless to complicate the code with it.

**Comment by Grounded0** [comment]
> We still don't have conclusive proof that 80-bit FPU emulation is required. If no DOS game uses it, it's rather pointless to complicate the code with it. Whether that library is excellent or not is beside the point.

Only [Critical Path (1993)](https://www.mobygames.com/game/3362/critical-path/) is proven to be extended precision related as it does checks using Win16 math lib before running that fail and I don't see many Critical Mass enthusiasts here. 😁

**Comment by Amaroq-Clearwater** [comment]
I'm not 100% on the details, but sometimes games compiled for Windows will include extended-precision instructions by mistake (the compiler’s fault). But as I understand it, this is pretty rare.

**Comment by Grounded0** [comment]
> Yes, and I haven't seen proof that the problems are FPU related. Identify the problem first, then think about the solution—always does the trick 😆

https://github.com/dosbox-staging/dosbox-staging/issues/610#issuecomment-2241047893

**Comment by Grounded0** [comment]
Critical Path just had its https://github.com/dosbox-staging/dosbox-staging/labels/CPU%2FFPU%20emulation label dropped as we don't know what's causing it failing to run on non-x86.

**Comment by Grounded0** [comment]
Closing this since we're currently at a state that all the connected tickets are either: resolved, we're fairly confident after thorough investigation they're not lack of extended precision issues or we can't prove that they're lack of extended precision issues.

Developments in this space can be followed with labels https://github.com/dosbox-staging/dosbox-staging/labels/CPU%2FFPU%20emulation and https://github.com/dosbox-staging/dosbox-staging/labels/non-x86.

I've spent considerable amount of time labelling our open and closed issues and PRs with both labels all the way back to 2020.
