### ISSUE TITLE
use_joy_calibration_hotkeys doesn't seem to work

### ISSUE THREAD

**Issue by LiquidProj3ct** [dosbox-staging/dosbox-staging#4229]
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### What operating system are you using?

Please select

### If other OS or Linux, please describe

Windows 10

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### What is your question and how can we help?

When I play some games, I think the joystick is too sensitive. 

I have activated the flag use_joy_calibration_hotkeys=true, and I see that when I use Ctrl-F1, I have the shortcuts for joystick calibration and sensitivity. 

However, while I’m piloting the airplane, I press Ctrl + arrow keys several times, and the joystick remains at the same sensitivity (I tried with Alt key too, but my problem is with the scale, and not with the offset). Nothing appears on the screen either, so I can’t set anything in the joy_x_calibration field.

I've tested with F-16 Combat Pilot, and Knights of the Sky. Am I doing something wrong?

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

**Comment by johnnovak** [comment]
@LiquidProj3ct Read the relevant wiki section and follow the calibration instructions:

https://github.com/dosbox-staging/dosbox-staging/wiki/Joysticks

Might be worthwhile to try a few joystick test programs referenced in the wiki and a couple of other games as well.

It could be a game issue too, e.g., you might need to lower the cycles setting substantially to 3000 or something, otherwise the game might misbehave (just like on hardware thst is too fast for the game).

**Comment by LiquidProj3ct** [comment]
@johnnovak Thanks. I found quite helpful the reference (I didn't know it exist), and now I can see the values changing when I Ctrl-Left/Right in the console. However, it seems they do not affect the game. 

However, I was expecting the scale parameter to reduce the joystick's sensitivity. But that doesn’t seem to be the case in F-16 Combat Pilot. I'm running the game with 1500 cycles, 386 and core simple, and timed=false. The plane keeps banking the same way, whether the scale is set to 0.002 or 100!

**Comment by johnnovak** [comment]
> [@johnnovak](https://github.com/johnnovak) Thanks. I found quite helpful the reference (I didn't know it exist), and now I can see the values changing when I Ctrl-Left/Right in the console. However, it seems they do not affect the game.
> 
> However, I was expecting the scale parameter to reduce the joystick's sensitivity. But that doesn’t seem to be the case in F-16 Combat Pilot. I'm running the game with 1500 cycles, 386 and core simple, and timed=false. The plane keeps banking the same way, whether the scale is set to 0.002 or 100!

Did you do this?

> Each tap will report X or Y calibration values you can set below. When you find parameters that work, quit the game, switch this setting back to disabled, and populate the reported calibration parameters.

Did you you copy the `x_calibration` and `y_calibration` values from the log window into the config, and then have you restarted the game?

**Comment by LiquidProj3ct** [comment]
To be honest, I didn’t configure it; I had only tried to manually alter the sensitivity of the X-axis by setting use_joy_calibration_hotkeys = true. Otherwise, what would be the point of that option?

I’ve tested it again now using the following settings:

```
[joystick]
use_joy_calibration_hotkeys = false
joy_x_calibration = 0.0198981,0.02
joy_y_calibration = auto
```

However, the X-axis response of my joystick still doesn’t change when I move it in the plane.

**Comment by johnnovak** [comment]
@LiquidProj3ct Can you try the joystick test program or other games as well to rule out some hardware or OS issue?

**Comment by LiquidProj3ct** [comment]
Ok, I've tried with:

Red Baron
Battlehawks 1942
Mig-29M Super Fulcrum
F-19 Stealth Figther

In all of them, I included the following lines:

```
[joystick]
use_joy_calibration_hotkeys = false
joy_x_calibration = 0.0198981,0.02
joy_y_calibration = auto
```

And in none of them did it have any effect (or at least I didn’t notice anything) when banking the plane. I want to add that I have a common.conf file for all games and a separate game.conf file for each game. It's in game.conf where I added the calibration lines. I start the games with this:

```
set SDL_WINDOWS_NO_CLOSE_ON_ALT_F4=1
start .\Staging\dosbox.exe -conf ..\..\scommon.conf -conf game.conf -noconsole
```

**Comment by LiquidProj3ct** [comment]
Oh, and my joystick (Logitech extreme 3D Pro) is working fine. I did the same with its own software and it works. I tried with IL2 1946 and, they game scaling, works fine too.

**Comment by johnnovak** [comment]
I've tested this with the `JOYSTICK.EXE` joystick checker tool included with Mig-29M Super Fulcrum. When I change the calibration via the hotkeys, the numbers in the joy checker tool definitely change, so this seems to be working.

Now, how useful this DOSBox-side joy calibration thing is—I don't know. Maybe it was never too useful in the first place. I wouldn't know as I don't play DOS games that require a joystick. Someone from the team ported it from DOSBox ECE I believe a while ago.

Probably you'll be better off using the calibration//configuration tool that came with your joystick for such adjustments. Usually these software can do more advanced things like remapping the curves per each axis, etc. Or maybe use some 3rd party joystick tweaker tool.

I'll leave this open, maybe someone who's into playing DOS games with a joystick can give you a better answer. I also encourage you to join our Discord channel and ask around there.

**Comment by interloper98** [comment]
I searched eXoDOS's GitHub issues for "joystick calibration", and @Python-Exoproject has fixed a handful of games (https://github.com/exoscoriae/eXoDOS/issues/4999):

Helter Skelter (1989) - Game is currently unplayable in exodos as you cant move left. As well as converting and resetting mapper I have fixed the issue using Staging's joystick calibration options.

Quasar (1990) - Game currently has a note about being hard to control. Using Staging, I was able to tweak the joystick calibration so this issue is fixed. 

Star Destroyer - Episode I (1986) - This game is currently unplayable in ECE\Vanilla\etc as the targeting reticule is stuck in the top left. Using Staging I have fixed this with is joystick calibration settings.

Maybe @Python-Exoproject has some techniques to get this one working, too.

**Comment by interloper98** [comment]
@johnnovak , the `joycheck.exe` you recommended worked perfectly. 

I'm using a GameCube joystick (but it probably doesn't matter):
```
2025-03-19 17:16:04.099 | MAPPER: Initialised limited MAYFLASH GameCube Controller Adapter with 6 axes, 16 buttons, and 1 hat(s)
2025-03-19 17:16:04.100 | MAPPER: Loaded default key bindings
```

The `use_joy_calibration_hotkeys = true` let me step down the X scale (Ctrl + left-arrow), then used the X offset (Alt + right-arrow) to shift the crosshairs back into the center, which tamped down the distance the joystick travels along the X axis.

Here's how it looks (w/ CPU cycles at default 3000):

```
[joystick]
joysticktype = 2axis
timed  = true
deadzone = 1
joy_x_calibration = 0.25,0.31
```

https://github.com/user-attachments/assets/4c98b745-7e8e-4d28-8af2-c8c9703460a8

The F-16 now banks like an Airbus A350 😄, and I was taken out by enemy fire during a dogfight, so for me, I need the twitchier defaults.

@LiquidProj3ct, here's my full config for the game. Note I used the default cycles of 3000 - the joystick seems to run as a function of cycles, so if you want to keep with 1500 cycles, then you probably need to redo the calibration:

```ini
[dosbox]
machine = ega
memsize = 1
vmemsize = 512

[cpu]
cpu_cycles = 3000

[midi]
mpu401 = off
mididevice = none

[sblaster]
sbtype = off

[gus]
gus = off

[ethernet]
ne2000 = off

[joystick]
joysticktype = 2axis
timed = true
deadzone = 1
joy_x_calibration = 0.25,0.31
# joy_y_calibration = auto
# use_joy_calibration_hotkeys = true

[speaker]
pcspeaker = discrete

[dos]
ems = off
xms = off
umb = off

[mouse]
mouse_capture = onstart
mouse_sensitivity = 175
mouse_raw_input = true
dos_mouse_immediate = true

[autoexec]
@echo off
a:
autotype -w 0.1 e , space space x enter
f16
```

**Comment by LiquidProj3ct** [comment]
@interloper98 and @johnnovak thank you very much for your time and help. Indeed, with that configuration, the F16 banks slowly. 

However, I think I have found the problem: For 99% of my games, I play with `timed=false`, because most of them work much better and do not depend on the `cpu_cycles `(when `timed=true` and you change the `cpu_cycles`, the joystick calibration gets lost). If you try using timed=false, you will see that the joy_x_calibration does not work.

**Comment by LiquidProj3ct** [comment]
May it be a bug? or maybe  `joy_x_calibration `only should work with games which are compatible with `timed=true`?

**Comment by johnnovak** [comment]
> For 99% of my games, I play with `timed=false`, because most of them work much better and do not depend on the `cpu_cycles `(when `timed=true` and you change the `cpu_cycles`, the joystick calibration gets lost).

How exactly do they work "much better"? FYI, with `timed = true`, the real-hardware behaviour is accurately emulated. This is explained [in this post](https://www.vogons.org/viewtopic.php?p=106658#p106658):

_**timed=true** is more precise emulation that takes computer speed (= dosbox cycles) into account when calculating joystick movement. **Timed=false** is old behaviour before the patch. For some reason, some games like the old behavior (Tie Fighter), others need timed=true (Descent 2). Leave the default, if you have problems, try timed=false._

On a real DOS machine, the CPU speed is fixed, so CPU-speed dependent in-game calibration routines will be thrown off if you you go and change the cycles setting after the calibration. This is how the games behave on a real hardware DOS machine too. Most likely using the "turbo" button on real hardware would also throw the in-game calibration off.

The learning from this is that `timed=false` is a hack, and should be only used as a last resort workaround as it might help with some games. I will include all this extra info in the description of the `timed` setting.

> If you try using timed=false, you will see that the joy_x_calibration does not work.

Might be the case, we'll need to test then document accordingly.

> May it be a bug? or maybe `joy_x_calibration `only should work with games which are compatible with `timed=true`?

As per above.

**Comment by LiquidProj3ct** [comment]
> How exactly do they work "much better"? FYI, with timed = true, the real-hardware behaviour is accurately emulated. 

With some older games, it’s especially difficult to get the number of `cpu_cycles `just right. Being able to adjust those cycles while still having the joystick work during gameplay is a great advantage and gives the experience a more "solid" feel. 

I also seem to recall that all my games (vehicle simulators) work well with `timed=false`. With `timed=true`, some of them had issues. That’s why I thought it was a good idea to set it to `false` by default.

> I will include all this extra info in the description of the timed setting.

Yes, it will help!

> We'll need to test then document accordingly.

It will help too.

Thanks for your replies, I think we can close this now if you want :)
