### ISSUE TITLE
window on wayland loses cursor capture after entering the keymapper

### ISSUE THREAD

**Issue by jiffygist** [dosbox-staging/dosbox-staging#4257]
### Are you using the latest DOSBox Staging version?

- [x] I have checked and I'm using the latest release.

### Different version than latest?

git

### What operating system are you using?

Linux x86_64

### If other OS or Linux, please describe

wayland, river wm

### Are you running DOSBox Staging on a native OS?

- [x] I am running Staging on a native OS

### Have you checked that no other similar issue already exists?

- [x] I have searched and have not found similar issues.

### A clear and concise description of what the bug is

After I enter the keymapper with CTRL+F1 the cursor is not captured anymore and cannot be recaptured (tried CTRL+F10) so I have to restart dosbox.

video: https://github.com/user-attachments/assets/e870ce4e-688c-49eb-b0d1-6836fde1eb13

does not happen on xorg

### Your configuration

```ini
pretty much the default
```

### Provide a log

```text

```

### Code of conduct and contributing guidelines

- [x] Yes, I agree.

**Comment by jiffygist** [comment]
> SDL_VIDEODRIVER=x11 ./dosbox should be a workaround. It uses XWayland and does not have this bug.

Yeah that works, thanks

> For me, I can release the mouse capture and then re-capture it and it goes back to normal (hit Ctrl+F10 twice). If Ctrl+F10 isn't working, try the middle mouse button to release capture and then click back into the window to re-capture.

Doesn't work

**Comment by johnnovak** [comment]
@weirddan455 @FeralChild64 Is this something you guys wanna fix, or shall I close it with out of scope? No idea about the Wayland / X11 situation on Linux. Do we support both, are both popular?

**Comment by weirddan455** [comment]
IMO we need to support both. I don’t have any stats but it almost feels 50/50 for native Wayland or X11/XWayland.

I’ll look into this at some point but it’s a mapper bug. Could just throw it on that mega ticket with the rest of the mapper bugs.

**Comment by johnnovak** [comment]
> IMO we need to support both. I don’t have any stats but it almost feels 50/50 for native Wayland or X11/XWayland.

Okay, I'll make a mental note about this for the next Wayland ticket 😄 
 
> I’ll look into this at some point but it’s a mapper bug. Could just throw it on that mega ticket with the rest of the mapper bugs.

You can certainly do that, but the mapper rewrite is several years away. Up to you, but you guys might wanna fix smaller Linux issues like this before that happens (I'd certainly want to fix it now if Windows or macOS was affected).

**Comment by weirddan455** [comment]
Well the problem isn't in mapper code (thank god). It's in this `MOUSE_NotifyTakeOver()` function call. This patch reproduces the problem by changing Ctrl+F1 to stub out the mapper and only run that function (like the real mapper does at the start and end).

```
diff --git a/src/gui/sdl_mapper.cpp b/src/gui/sdl_mapper.cpp
index 988eba91a..c7e216ae5 100644
--- a/src/gui/sdl_mapper.cpp
+++ b/src/gui/sdl_mapper.cpp
@@ -2997,8 +2997,8 @@ void MAPPER_Run(bool pressed) {
                return;
        }
 
-       // In case mapper deletes the key object that ran it
-       PIC_AddEvent(MAPPER_RunEvent,0);        
+       MOUSE_NotifyTakeOver(true);
+       MOUSE_NotifyTakeOver(false);
 }
 
 SDL_Surface* SDL_SetVideoMode_Wrap(int width,int height,int bpp,uint32_t flags);
```

To reproduce

1. Be on a Wayland compositor. KDE Plasma 5.27.5 for me.
2. `export SDL_VIDEODRIVER=wayland`
3. Launch Staging
4. Capture the mouse by clicking in the window.
5. Press Ctrl+F1.
6. If you apply the above patch, the problem happens immediately. Otherwise, close the mapper.

The mouse then enters a state where it shows as captured on the title bar and the cursor disappears while hovering over the DOSBox window but is still allowed to escape the window and re-appears after leaving window bounds.

Playing a game that uses the mouse while in the state has strange results. The in-game mouse cursor gets de-synced from where the "real" system cursor is.

On my system I can correct this by uncapturing and re-capturing the mouse but apparently that does not work on all window managers.

**Comment by weirddan455** [comment]
I can look into this more later maybe but I think @FeralChild64 is more familiar with that mouse code.

**Comment by johnnovak** [comment]
> I can look into this more later maybe but I think [@FeralChild64](https://github.com/FeralChild64) is more familiar with that mouse code.

Sounds like a @FeralChild64 issue, yeah 😄

**Comment by FeralChild64** [comment]
On _KDE 6_ I am getting similar results as @weirddan455.

@johnnovak Probably most of the "consumer" distros have already switched to Wayland as default, not sure how much decided to use a native wayland video driver in SDL, though.

**Comment by FeralChild64** [comment]
I'm 99% sure this is SDL wayland driver oddity - I've added logs to trace `MOUSE_NotifyTakeOver` / `GFX_SetMouseCapture` / `GFX_SetMouseRawInput` / `GFX_SetMouseVisibility` calls:

```
(here I am starting the mapper)
2025-03-29 12:27:08.686 | XXX MOUSE_NotifyTakeOver true
2025-03-29 12:27:08.686 | XXX GFX_SetMouseCapture false
2025-03-29 12:27:08.686 | XXX GFX_SetMouseRawInput false
2025-03-29 12:27:08.686 | XXX GFX_SetMouseVisibility true

(here I am quitting the mapper)
2025-03-29 12:27:18.460 | XXX MOUSE_NotifyTakeOver false
2025-03-29 12:27:18.460 | XXX GFX_SetMouseCapture true
2025-03-29 12:27:18.460 | XXX GFX_SetMouseRawInput true
2025-03-29 12:27:18.460 | XXX GFX_SetMouseVisibility false
```

**Comment by FeralChild64** [comment]
@weirddan455, @jiffygist Is it just me, or changing config option `mouse_raw_input = false` makes the problem disappear?

**Comment by weirddan455** [comment]
> Is it just me, or changing config option mouse_raw_input = false makes the problem disappear?

Yeah, that fixes it.

**Comment by FeralChild64** [comment]
OK, I'll collect as much information as possible and report this upstream.

**Comment by johnnovak** [comment]
@FeralChild64 What's the status of this? Do we need to keep this open?

**Comment by gera2342** [comment]
Sorry for not replying. The problem still appears for me whether I have `mouse_raw_input = off` or `on`. On wayland videodriver that is.

**Comment by Grounded0** [comment]
I'm not including this on mapper megaticket (#3075) since well... It could be an SDL issue, a Wayland issue, or both. 😁

**Comment by johnnovak** [comment]
> I'm not including this on mapper megaticket ([#3075](https://github.com/dosbox-staging/dosbox-staging/issues/3075)) since well... It could be an SDL issue, a Wayland issue, or both. 😁

Yeah, it's a Linux issue.

**Comment by FeralChild64** [comment]
> [@FeralChild64](https://github.com/FeralChild64) What's the status of this? Do we need to keep this open?

I have completely forgotten about this one, sorry. Unfortunately, I won't have time to look at it at least till the weekend.

**Comment by FeralChild64** [comment]
Sorry, I have no idea when I'll have time to get back to this issue.

**Comment by johnnovak** [comment]
> Sorry, I have no idea when I'll have time to get back to this issue.

No prob 😄 I just periodically do a random search in the issue tracker when the number of open issues starts to get close to 200 and start pinging people 😆

**Comment by FeralChild64** [comment]
I have just retested it with the current code and SDL version 2.32.8 - mouse can be recaptured now, but you need to do it "twice", as the mouse code thinks the mouse is captured, while in reality it is not. Still to be investigated on our side.

**Comment by FeralChild64** [comment]
The keymapper (`MAPPER_DisplayUI()` function) ends with:

```c++
GFX_ResetScreen();
MOUSE_NotifyTakeOver(false);
```

And the `MOUSE_NotifyTakeOver` tries to restore the captured mouse by calling` GFX_SetMouseCapture(true)`, which in turn calls `SDL_SetRelativeMouseMode(SDL_TRUE)` - but for some reason this SDL call does not work.

[edit] It seems the `SDL_HINT_MOUSE_RELATIVE_MODE_WARP` and `SDL_SetRelativeMouseMode` do not play well together on Wayland video driver; definitely to be reported upstream for further analysis (just not today - it's getting really late...).

**Comment by FeralChild64** [comment]
Reported the problem upstream.

**Comment by weirddan455** [comment]
I can confirm what @FeralChild64 said here:

> Problem does not reproduce for me if I use libsdl2-2.32.56 package (which is a compatibility layer) on top of libsdl3-3.2.24

I'm on Arch Linux now with KDE 6.4.5 Wayland building with system libs. Arch has removed SDL 2 from the repos and replaced it with `sdl2-compat` (same versions as mentioned). I can no longer reproduce this bug.

Worst case, this bug will be solved when we migrate to SDL 3.

**Comment by Kontrabant** [comment]
This has been fixed upstream and will be in the next bugfix release of SDL2.

sdl2-compat has also been updated to alias the relative mode warp hint to the SDL3 relative system scale hint, so it will send accelerated motion deltas to match the behavior of setting the old relative mode warp hint, which it previously didn't.

**Comment by gera2342** [comment]
I was too quick to say it didn't work

That indeed fixes it, thanks @Kontrabant!

**Comment by Kontrabant** [comment]
Welcome!

**Comment by johnnovak** [comment]
Keeping the ticket open until we upgrade to the new SDL2 version with the fix. Technically, it's not fixed yet in our `main` branch 😄
